version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo Packaging Lambda function...
      - cd lambda
      - zip -r ../lambda.zip .
      - cd ..
  post_build:
    commands:
      - echo Uploading lambda.zip to S3...  # here i code for to build zip file and save in my bucket
      - aws s3 cp lambda.zip s3://aws-devops-starter-bucket/lambda.zip
      - echo Build completed.

artifacts:
  files:
    - cloudformation/**/* # here changes for saving my file to s3bucket
    - lambda/**/*
    - frontend/**/*
    - buildspec.yml
