version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r lambda/requirements.txt -t lambda/ || true
  build:
    commands:
      - echo Zipping Lambda function...
      - cd lambda && zip -r ../lambda.zip . && cd ..
  post_build:
    commands:
      - echo Uploading artifacts to S3 bucket: $ARTIFACT_BUCKET
      - test -n "$ARTIFACT_BUCKET" || (echo "ERROR: ARTIFACT_BUCKET env var is required" && exit 1)
      - aws s3 cp lambda.zip s3://$ARTIFACT_BUCKET/lambda.zip --exact-timestamps
      - aws s3 sync cloudformation/ s3://$ARTIFACT_BUCKET/cloudformation/ --exact-timestamps --exclude "*" --include "*.yml"
      - echo Build completed successfully.
artifacts:
  files:
    - cloudformation/*.yml
